services: 
  backend:
    build: ./
    ports:
      - "8000:8000"
    # volumes:
    #   - ./backend:/app
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://postgres:test123@db:5432/hangoutdb


      # - FLASK_APP=app.py
      # - FLASK_ENV=development
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules
  # db:
  #   image: postgres:15
  #   container_name: hangoutdb_container1
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: Aa123456789
  #     POSTGRES_DB: hangoutdb
  #   ports:
  #     - "5432:5432"
  db:
    image: postgres:15
    container_name: postgres_container2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: hangoutdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
 
volumes:
  postgres_data: